#!/bin/sh

# If we're lucky /tmp is in tmpfs and thus faster
TMPFILE=$(mktemp)

delete() {
	sed "s/[ ]*${1}[ ]*//g" -i $TMPFILE
}

delete_elem() {
	delete "<${1}>[^<]*<\/${1}>"
}

replace() {
	sed "s/[ ]*${1}[ ]*/${2}/g" -i $TMPFILE
}

rm -f JMdict_e.gz
wget --show-progress ftp://ftp.monash.edu.au/pub/nihongo/JMdict_e.gz
gzip -cdfv JMdict_e.gz > JMdict.xml
rm -f JMdict_e.gz

echo
echo "Preparing JMdict"

# Delete header, then put everything into a single line and copy to working file
sed '/<?xml version=/,/<JMdict>/d' JMdict.xml | tr "\n" " " > $TMPFILE

# Split file one entry per line, mostly (header is still on the first line)
replace "<\/entry>" "\n"

# Delete last line
sed '$ d' -i $TMPFILE

# Remove non-english glosses
delete "<gloss xml:lang=\"[a-z]*\">[^<]*<\/gloss>"

# Format entry number
replace "<entry>[ ]*<ent_seq>\([^<]*\)<\/ent_seq>" "\1|"

# Unused elements
delete_elem "ke_pri"
delete_elem "re_pri"
delete_elem "xref"

echo "Processing kanji data"

# Kanji
# Move ke_inf inside keb
replace "<\/keb>[ ]*<ke_inf>&\([^;]*\);<\/ke_inf>" " <i>\1<\/i><\/keb>"
replace "<\/keb>[ ]*<ke_inf>&\([^;]*\);<\/ke_inf>" " <i>\1<\/i><\/keb>"
# Delete <k_ele> and </k_ele>
delete "<k_ele>"
delete "<\/k_ele>"
# Merge kebs
replace "<\/keb>[ ]*<keb>" "\\\n"
# Delete remaining <keb> and </keb>
delete "<keb>"
delete "<\/keb>"

echo "Processing reading data"

# Reading
# FIXME: deal with these in a better way
delete_elem "re_restr"
delete "<re_nokanji\/>"
# Move re_inf inside reb
replace "<\/reb>[ ]*<re_inf>&\([^;]*\);<\/re_inf>" " <i>\1<\/i><\/reb>"
replace "<\/reb>[ ]*<re_inf>&\([^;]*\);<\/re_inf>" " <i>\1<\/i><\/reb>"
# Delete <r_ele> and </r_ele>
delete "<r_ele>"
delete "<\/r_ele>"
# Merge rebs
replace "<\/reb>[ ]*<reb>" "\\\n"
# Delete remaining <reb> and </reb>, add separator
replace "<reb>" "|"
replace "<\/reb>[ ]*<sense>" "|"

echo "Processing sense data"

# Sense
delete_elem "ant"
delete "<lsource [^>]*>[^<]*<\/lsource>"
delete "<lsource [^>]*\/>"

replace "<\/stag[kr]>[ ]*<stag[kr]>" ", "
replace "<\/stag[kr]>" ": "
delete "<stag[kr]>"

replace "<pos>&\([^;]*\);<\/pos>" "<i>\1<\/i> "
replace "<misc>&\([^;]*\);<\/misc>" "<i>\1<\/i> "
replace "<dial>&\([^;]*\);<\/dial>" "<i>\1<\/i> "
replace "<field>&\([^;]*\);<\/field>" "<i>\1<\/i> "

replace "<\/gloss>[ ]*<gloss>" "; "
replace "<\/i>[ ]*<gloss>" "<\/i>\\\n"
replace "<\/i><i>" "<\/i> <i>"
replace "<\/gloss>[ ]*<\/sense>[ ]*<sense>" ".\\\n"
replace "<s_inf>" " ["
replace "<\/s_inf>" "]"
replace "<\/gloss>[ ]*<\/sense>" "."
delete "<gloss>"

replace "\]\([^ ]\)" "\] \1"
replace ",\([^ ]\)" ", \1"
replace ":\([^ ]\)" ": \1"

echo "Adding kanji and entity definitions"

IFS=$'\n'
rm JMdict.csv
for entry in $(cat $TMPFILE); do
	echo -n ${entry} >> JMdict.csv
	for char in $(echo ${entry} | sed -e 's/\(.\)/\1\n/g' | awk '!seen[$0]++'); do
		if [[ ${char} != "\\" ]] && [[ ${char} != "." ]] && [[ ${char} != "[" ]]; then
			kanji_entry=$(grep "^${char}|" ../KANJIDIC2/kanjidic2.csv)
			if [[ ${#kanji_entry} != "0" ]]; then
				echo -n "\\n${kanji_entry}" | sed -e 's/|/ /g' -e 's/  / /g' >> JMdict.csv
			fi
		fi
	done
	for entity in $(echo ${entry} | sed 's/[^<]*<i>\([^<]*\)<\/i>[^<]*/\1\n/g' | awk '!seen[$0]++'); do
		echo -n "\\n<i>${entity}</i>" $(grep "^<!ENTITY ${entity} \"" JMdict.xml | cut -d '"' -f 2) >> JMdict.csv
	done
	echo >> JMdict.csv
done

rm -f $TMPFILE
echo
